# Generated by Django 5.2.7 on 2025-10-16 21:03

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_courts', to='quadras.category'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='week_days_open',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Segunda-Feira'), (1, 'Terça-Feira'), (2, 'Quarta-Feira'), (3, 'Quinta-Feira'), (4, 'Sexta-Feira'), (5, 'Sábado'), (6, 'Domingo')], default=None, max_length=22),
        ),
        migrations.AlterField(
            model_name='scheduleexception',
            name='courts',
            field=models.ManyToManyField(related_name='court_exceptions', to='quadras.court'),
        ),
    ]
